### ISSUE TITLE
Error in Multi-GPUs inference of mochi

### ISSUE THREAD

**Issue by guankaisi** [xdit-project/mochi-xdit#24]
```
(MultiGPUContext pid=3407) Traceback (most recent call last):
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/site-packages/torch/_inductor/compile_worker/__main__.py", line 41, in main
(MultiGPUContext pid=3407)     SubprocMain(args.workers, read_fd, write_fd).main()
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/site-packages/torch/_inductor/compile_worker/subproc_pool.py", line 167, in __init__
(MultiGPUContext pid=3407)     _warm_process_pool(self.pool, nprocs)
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/site-packages/torch/_inductor/compile_worker/subproc_pool.py", line 241, in _warm_process_pool
(MultiGPUContext pid=3407)     pool._adjust_process_count()
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/concurrent/futures/process.py", line 683, in _adjust_process_count
(MultiGPUContext pid=3407)     p.start()
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/multiprocessing/process.py", line 121, in start
(MultiGPUContext pid=3407)     self._popen = self._Popen(self)
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/multiprocessing/context.py", line 277, in _Popen
(MultiGPUContext pid=3407)     return Popen(process_obj)
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
(MultiGPUContext pid=3407)     self._launch(process_obj)
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/multiprocessing/popen_fork.py", line 66, in _launch
(MultiGPUContext pid=3407)     self.pid = os.fork()
(MultiGPUContext pid=3407) BlockingIOError: [Errno 11] Resource temporarily unavailable
(MultiGPUContext pid=3407) Exception in initializer:
(MultiGPUContext pid=3407) Traceback (most recent call last):
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/concurrent/futures/process.py", line 230, in _process_worker
(MultiGPUContext pid=3407)     initializer(*initargs)
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/site-packages/torch/_inductor/compile_worker/watchdog.py", line 28, in _async_compile_initializer
(MultiGPUContext pid=3407)     _watchdog_thread.start()
(MultiGPUContext pid=3407)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/threading.py", line 928, in start
(MultiGPUContext pid=3407)     _start_new_thread(self._bootstrap, ())
(MultiGPUContext pid=3407) RuntimeError: can't start new thread
```
I have 8*80GB A800 and cpus with 64 cores, why still my machine is out of resources?

**Comment by feifeibear** [comment]
Could you provide the launching script?

The error indicates a resource exhaustion issue (e.g., threads or processes). To resolve this:

1. **Increase system resource limits**:
   - Modify `/etc/security/limits.conf` to increase thread or process limits.
   - Use `ulimit -u` to increase the maximum number of user processes.

2. **Reduce parallelism**:
   - Decrease the number of worker threads or processes in your code.

3. **Check for resource leaks**:
   - Ensure no runaway processes or threads are consuming resources.

4. **Reboot or restart services**:
   - Free up resources by rebooting the system or restarting affected services.

5. **Upgrade hardware**:
   - If the workload exceeds system capacity, consider upgrading CPU or memory.

Let me know if you need further assistance!

**Comment by guankaisi** [comment]
Thank you for your reply. My inference script is 
```
export CUDA_VISIBLE_DEVICES=0,1,2,3,4
python3 cli.py --model_dir "/fs/fast/share/aimind_files/video_eval/models/mochi-1" --prompt "A dog is flying in the sky." \
 --use_xdit --ulysses_degree 2 --ring_degree 2
```

**Comment by xibosun** [comment]
I cannot run your command because (1) the command sets 5 GPUs to be visible but the degree of parallelism is ulysses x ring = 4 (2x2=4); (2) the default sequence length in mochi (14310) cannot divided by 4. Would you please try the following command.
```
export CUDA_VISIBLE_DEVICES=0,1,2,3
python3 cli.py --model_dir /cfs/dit/mochi-1-preview --prompt "a cat is playing with a dog" --use_xdit --ulysses_degree 2 --ring_degree 1 --cfg_parallel
```

**Comment by guankaisi** [comment]
Sorry for giving an incorrect script! I have run the command 
```
export CUDA_VISIBLE_DEVICES=0,1,2,3
python3 cli.py --model_dir "/fs/fast/share/aimind_files/video_eval/models/mochi-1" --prompt "a cat is playing with a dog" --use_xdit --ulysses_degree 2 --ring_degree 1 --cfg_parallel
```
But I meet the same error when loading text encoder
```
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/site-packages/torch/_inductor/compile_worker/__main__.py", line 41, in main
(MultiGPUContext pid=58998)     SubprocMain(args.workers, read_fd, write_fd).main()
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/site-packages/torch/_inductor/compile_worker/subproc_pool.py", line 167, in __init__
(MultiGPUContext pid=58998)     _warm_process_pool(self.pool, nprocs)
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/site-packages/torch/_inductor/compile_worker/subproc_pool.py", line 241, in _warm_process_pool
(MultiGPUContext pid=58998)     pool._adjust_process_count()
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/concurrent/futures/process.py", line 683, in _adjust_process_count
(MultiGPUContext pid=58998)     p.start()
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/multiprocessing/process.py", line 121, in start
(MultiGPUContext pid=58998)     self._popen = self._Popen(self)
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/multiprocessing/context.py", line 277, in _Popen
(MultiGPUContext pid=58998)     return Popen(process_obj)
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
(MultiGPUContext pid=58998)     self._launch(process_obj)
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/multiprocessing/popen_fork.py", line 66, in _launch
(MultiGPUContext pid=58998)     self.pid = os.fork()
(MultiGPUContext pid=58998) BlockingIOError: [Errno 11] Resource temporarily unavailable
(MultiGPUContext pid=58998) Exception in initializer:
(MultiGPUContext pid=58998) Traceback (most recent call last):
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/concurrent/futures/process.py", line 230, in _process_worker
(MultiGPUContext pid=58998)     initializer(*initargs)
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/site-packages/torch/_inductor/compile_worker/watchdog.py", line 28, in _async_compile_initializer
(MultiGPUContext pid=58998)     _watchdog_thread.start()
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/threading.py", line 928, in start
(MultiGPUContext pid=58998)     _start_new_thread(self._bootstrap, ())
(MultiGPUContext pid=58998) RuntimeError: can't start new thread
(MultiGPUContext pid=58998) Exception in initializer:
(MultiGPUContext pid=58998) Traceback (most recent call last):
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/concurrent/futures/process.py", line 230, in _process_worker
(MultiGPUContext pid=58998)     initializer(*initargs)
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/site-packages/torch/_inductor/compile_worker/watchdog.py", line 28, in _async_compile_initializer
(MultiGPUContext pid=58998)     _watchdog_thread.start()
(MultiGPUContext pid=58998)   File "/fs/fast/share/aimind_files/conda/envs/mochi-xdit/lib/python3.10/threading.py", line 928, in start
(MultiGPUContext pid=58998)     _start_new_thread(self._bootstrap, ())
(MultiGPUContext pid=58998) RuntimeError: can't start new thread
```
It seems that some problems with `ray` for multi-process. It's interesting that if I run the command for 2 GPUS
```
export CUDA_VISIBLE_DEVICES=0,1
python3 inference_mochi.py \
    --model_dir "/fs/fast/share/aimind_files/video_eval/models/mochi-1" \
    --prompt /fs/fast/share/aimind_files/video_eval/prompt_sample/prompts_sample.json \
    --use_xdit --ulysses_degree 2 --ring_degree 1 \
```
It will work well. However, with 4 or more GPUs, whether with `--cfg_parallel` or not, it will meet the same error.

**Comment by feifeibear** [comment]
Are you occupying the entire machine? I suspect it might be due to some environmental issues, such as insufficient resources preventing access to them. We can successfully run it using this command.

**Comment by guankaisi** [comment]
@feifeibear Thank you for your reply. Could you let me know the specifications of your machine’s GPU and CPU?

**Comment by feifeibear** [comment]
We test it on 8xL40 and AMD EPYC 9K84 96-Core CPU.
